### ISSUE TITLE
安卓真机无法运行

### ISSUE THREAD

**Issue by frankxzx** [williamwen1986/flutter_luakit_demo#2]
使用设备: 小米 6
操作系统: 安卓 8.0

<img width="1744" alt="Screenshot 2019-04-16 下午4 25 57" src="https://user-images.githubusercontent.com/8599205/56193927-5c1e5a80-6064-11e9-92a4-c02d054367fb.png">

iOS 真机可以正常运行，但是有一个小问题第一次运行的时候会有网络权限提示，会导致接口无法访问然后就是列表空白，有什么可以解决的思路吗？

**Comment by williamwen1986** [comment]
请问android运行不了有提示错误吗？ ios网络权限先申请权限再去load数据就可以了，这个是app自己业务逻辑，这个demo没做处理

**Comment by williamwen1986** [comment]
> 使用设备: 小米 6
> 操作系统: 安卓 8.0
> 
> <img alt="Screenshot 2019-04-16 下午4 25 57" width="1744" src="https://user-images.githubusercontent.com/8599205/56193927-5c1e5a80-6064-11e9-92a4-c02d054367fb.png">
> 
> iOS 真机可以正常运行，但是有一个小问题第一次运行的时候会有网络权限提示，会导致接口无法访问然后就是列表空白，有什么可以解决的思路吗？

请问android运行不了有提示错误吗？ ios网络权限先申请权限再去load数据就可以了，这个是app自己业务逻辑，这个demo没做处理

**Comment by williamwen1986** [comment]
打开android 项目，不要打开flutter项目，我们现在的so暂时不支持arm64-v8a
