### ISSUE TITLE
Execution failed for task ':app:preDebugBuild'.

### ISSUE THREAD

**Issue by Larpoux** [williamwen1986/flutter_luakit_demo#3]
When I try to run the demo, I get the following error message 👎 

Execution failed for task ':app:preDebugBuild'.
> Android dependency 'com.github.williamwen1986:LuakitJitpack' has different version for the compile (1.0.7) and runtime (1.0.9) classpath. You should manually set the same version via DependencyResolution

**Comment by williamwen1986** [comment]
check out and now is ok

**Comment by Larpoux** [comment]
Thank you very much Williamwen. 
You was very prompt to fix my issue :-)

I am really interested by LuaKit and I am considering working with it.

Do you think possible to modify the Lua/Flutter interface so that a Lua Script can call the Flutter library ?


Regards

/Larpoux

**Comment by williamwen1986** [comment]
luakit provide notification function，you can post a notification from lua and receive in flutter so you can call any flutter library from lua

**Comment by williamwen1986** [comment]
lua：

lua_notification.postNotification(3,
{
    lua1 = "lua123",
    lua2 = "lua234"
})

flutter ：

FlutterLuakitPlugin.addLuaObserver(3, notify);
