### ISSUE TITLE
Demo on Android Simulator

### ISSUE THREAD

**Issue by Larpoux** [williamwen1986/flutter_luakit_demo#5]
When I start the demo on the iOS simulator, everything are OK.

When I start the demo on the Android simulator I get the following error message 👎 

Syncing files to device Android SDK built for x86...
Error writing "build/flutter_assets/AssetManifest.json" to DevFS: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:60285/
Error writing "build/flutter_assets/FontManifest.json" to DevFS: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:60285/
Error writing "build/flutter_assets/LICENSE" to DevFS: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:60285/
Error writing "build/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf" to DevFS: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:60285/
Error writing "build/flutter_assets/fonts/MaterialIcons-Regular.ttf" to DevFS: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:60285/

**Comment by williamwen1986** [comment]
luakit do not provide x86 Architecture so，you should debug on android real phone， not on simulator
