### ISSUE TITLE
如何动态加载lua脚本

### ISSUE THREAD

**Issue by jczh98** [williamwen1986/flutter_luakit_demo#6]
不同于 #4 ，程序在运行时加载脚本，以及IOS如何加载document的脚本

**Comment by williamwen1986** [comment]
可以在你的工程项目调用luaSetPackagePath(pathChar);设置lua工程路径

**Comment by williamwen1986** [comment]
https://github.com/williamwen1986/Luakit/blob/bbceb574aebf3537b1df145f93db88800f138d85/LuaKitProject/IOSFrameWork/include/lua_helpers.h
方法在这个头文件里面

**Comment by williamwen1986** [comment]
startLuakit之前设置就可以
